# Generated by Django 6.0.1 on 2026-01-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('N', 'Novo'), ('U', 'Usado')], max_length=1)),
                ('preço', models.CharField(max_length=10)),
            ],
        ),
    ]
