# Generated by Django 6.0.1 on 2026-01-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolemodel',
            name='descrição',
            field=models.TextField(blank=True, null=True),
        ),
    ]
