# Generated by Django 6.0.1 on 2026-01-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_consolemodel_descrição'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolemodel',
            name='imagem',
            field=models.ImageField(default='oi', upload_to='consoles/'),
            preserve_default=False,
        ),
    ]
